Public Class Form1

    Dim draggable As Boolean
    Dim mousex As Integer
    Dim mousey As Integer
    Dim xs As Integer
    Private Sub PictureBox2_Click(sender As Object, e As EventArgs) Handles PictureBox2.Click
        Me.Close()

    End Sub


    Private Sub Form1_MouseMove(sender As Object, e As MouseEventArgs) Handles Me.MouseMove
        If draggable = True Then
            Me.Top = Cursor.Position.Y - mousey
            Me.Left = Cursor.Position.X - mousex
        End If
    End Sub

    Private Sub Form1_MouseDown(sender As Object, e As MouseEventArgs) Handles Me.MouseDown
        draggable = True
        mousex = Cursor.Position.Y - Me.Left
        mousey = Cursor.Position.X - Me.Top
    End Sub

    Private Sub Form1_MouseUp(sender As Object, e As MouseEventArgs) Handles Me.MouseUp
        draggable = False
    End Sub

    Private Sub BunifuFlatButton1_Click(sender As Object, e As EventArgs) Handles BunifuFlatButton1.Click
        Bid.Visible = True
        BidTeam.Visible = True
        Bid.Text = Bidtxtbx.Text
        BidTeam.Text = ListBox1.SelectedItem


    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Bidtxtbx.Text = ""
        PictureBox3.SizeMode = PictureBoxSizeMode.Zoom
        Lblname.Text = ""
        Lblbat.Text = ""
        Lblball.Text = ""
        LBLwick.Text = ""
        Lblach.Visible = False
        Lblach.Text = ""
        Lbldept.Text = ""
        lblallrounder.Text = ""
        Label2.Text = ""
        PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\test.png")
    End Sub

    Private Sub btnregsubmit_Click(sender As Object, e As EventArgs) Handles btnregsubmit.Click
        xs = txtreg.Text
        Label2.Text = xs

        If xs = 1 Then

            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\1.jpg")
            Lblname.Text = "mohesh"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3rd BA"

            lblallrounder.Text = ""
        ElseIf xs = 2 Then

            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\2.jpg")
            Lblname.Text = "shailesh"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3rd BA"
            lblallrounder.Text = "YES"

        ElseIf xs = 3 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\3.JPG")
            Lblname.Text = "SUHAIL MUNEER"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCA"
            lblallrounder.Text = ""
        ElseIf xs = 4 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\4.jpg")
            Lblname.Text = "YUNITH "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,SPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = "YES"
        ElseIf xs = 5 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\5.jpeg")
            Lblname.Text = "NAWAZ"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCOM B"
            lblallrounder.Text = ""

        ElseIf xs = 6 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\6.jpg")
            Lblname.Text = "SHARATH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM A"
            lblallrounder.Text = ""
        ElseIf xs = 7 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\7.jpg")
            Lblname.Text = "ELVIN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 8 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\8.jpeg")
            Lblname.Text = "HUSAIN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 9 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\9.jpg")
            Lblname.Text = "NOUSHAD"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach1.Text = "1ST BA"
            Lbldept.Text = ""
            lblallrounder.Text = "YES"
        ElseIf xs = 10 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\10.jpeg")
            Lblname.Text = "MOHAMAD IMRAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "Medium ,Right arm"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 11 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\11.jpg")
            Lblname.Text = "RAFI"
            Lblbat.Text = ""
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 12 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\12.jpeg")
            Lblname.Text = "DHANUSH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM "
            lblallrounder.Text = ""
        ElseIf xs = 13 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\13.jpeg")
            Lblname.Text = "RAKSHITH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "SPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 14 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\14.jpeg")
            Lblname.Text = "VINITH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "SPIN,RIGTHARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 15 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\15.jpg")
            Lblname.Text = "ANKITH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCA"
            lblallrounder.Text = "YES"
        ElseIf xs = 16 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\16.jpg")
            Lblname.Text = "NIKHIL D'SOUZA"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCA"
            lblallrounder.Text = ""
        ElseIf xs = 17 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\17.jpg")
            Lblach.Visible = True
            Lblname.Text = "ABDUL RAHIM"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "SPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach.Text = "college team,2nd runners up in manglore university cricket,runner up in taluk level cricket"
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 18 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\18.jpeg")
            Lblname.Text = "HUNAIS"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 19 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\19.jpeg")
            Lblname.Text = "SINAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "SPIN"
            LBLwick.Text = ""
            Lblach.Text = "YCFC MUNDAJE: BEST BATSMAN"
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 20 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\20.jpeg")
            Lblname.Text = "AKASH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = ""
        ElseIf xs = 21 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\21.jpeg")
            Lblname.Text = "DIVIN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = ""
        ElseIf xs = 22 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\22.jpg")
            Lblname.Text = "MUSTAFA"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "LEGSPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 23 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblname.Text = "ROHAN D'SOUZA"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "OFF SPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = "YES"
        ElseIf xs = 24 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblname.Text = "IRSHAD"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach.Text = "Played many tournaments and legues in home town, won many local matches,achived individuals"
            Lbldept.Text = "3rd bcom"
            lblallrounder.Text = ""

        ElseIf xs = 25 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\25.jpeg")
            Lblname.Text = "DARSHAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCA"
            lblallrounder.Text = ""
        ElseIf xs = 26 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\26.jpg")
            Lblname.Text = "JIJO JACOB"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach.Text = "PPL-2018 : BEST WICKET KEEPER"
            Lbldept.Text = "2ND BCA"
            lblallrounder.Text = ""
        ElseIf xs = 27 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\27.jpeg")
            Lblname.Text = "VISHAL"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach.Text = "COLLEGE TEAM"
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 28 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\28.jpg")
            Lblname.Text = "ABDUL HASIB"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = "YES"
            Lblach.Text = "TEAM RFC : MAN OF THE SERIES"
            Lbldept.Text = "1ST BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 29 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\29.jpg")
            Lblname.Text = "AHMAD IRFAN"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach.Text = "SUNNATHKERE CRICKET CLUB "
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 30 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\30.jpg")
            Lblname.Text = "SHAHID SAWAF"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach.Text = "UNITED NAVOOR CLUB,BANGADY STRIKERS,SWAGATH MANJOTY"
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"

        ElseIf xs = 31 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\31.jpg")
            Lblname.Text = "JAVAD"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 32 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\32.jpg")
            Lblname.Text = "HARSHITHRAJ"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = "MEDIUM PHASE ,RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCA"
            lblallrounder.Text = ""
        ElseIf xs = 33 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\33.jpeg")
            Lblname.Text = "AZWIN ROSHAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = "YES"
        ElseIf xs = 34 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\34.jpg")
            Lblname.Text = "SUHAS"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 35 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\35.jpeg")
            Lblname.Text = "SACHETH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 36 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\36.jpg")
            Lblname.Text = "RAISAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 37 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\37.jpg")
            Lblname.Text = "SWASTHIK "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""

        ElseIf xs = 38 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\38.jpg")
            Lblname.Text = "CHIRAG"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 39 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\39.jpg")
            Lblname.Text = "KOUSHIK "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE ,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 40 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\40.jpg")
            Lblname.Text = "GOURAV "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 41 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\41.jpg")
            Lblname.Text = "HRUTHVIK "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 42 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\42.jpeg")
            Lblname.Text = "JEESHAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCA"
            lblallrounder.Text = ""
        ElseIf xs = 43 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\43.jpeg")
            Lblname.Text = "MOKSHITH"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = "COLLEGE TEAM PLAYER"
            Lbldept.Text = "2ND BA"
            lblallrounder.Text = ""
        ElseIf xs = 44 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\44.jpg")
            Lblname.Text = "RISHON "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach.Text = "SACRED HEART COLLEGE TEAM"
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 45 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\45.jpg")
            Lblname.Text = "SUJITH DS"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 46 Then
            Lblach.Visible = True
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\46.jpg")
            Lblname.Text = "NIKSHATH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach.Text = "11 STRIKERS,RED CHILLIES : Respresented university in cricket, College captain"
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 47 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\47.jpeg")
            Lblname.Text = "KIRAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "LEGSPIN,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 48 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\48.jpg")
            Lblname.Text = "PRATHIK"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 49 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\49.jpg")
            Lblach.Visible = True
            Lblname.Text = "VIJITH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach.Text = "Reresented college team for 3 years."
            Lbldept.Text = "2ND M-COM"
            lblallrounder.Text = "YES"
        ElseIf xs = 50 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\50.jpg")
            Lblname.Text = "KARTHIK HA"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BCA"
            lblallrounder.Text = "YES"
        ElseIf xs = 51 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\51.jpeg")
            Lblach.Visible = True
            Lblname.Text = "KISHORE "
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "SPIN"
            LBLwick.Text = "YES"
            Lblach.Text = "Blue boys gardady,baba friends goliyangady : runners up @ GPL-2022 and PPL-2021"
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 52 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\52.jpeg")
            Lblach.Visible = True
            Lblname.Text = "NAYAN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE"
            LBLwick.Text = ""
            Lblach.Text = "SACRED HEART COLLEGE TEAM"
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = "YES"
        ElseIf xs = 57 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\53.jpeg")
            Lblach.Visible = True
            Lblname.Text = "YATHEESHA"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "MEDIUM PHASE,RIGHT ARM"
            LBLwick.Text = "YES"
            Lblach.Text = "COLLEGE TEAM"
            Lbldept.Text = "2ND BCOM B"
            lblallrounder.Text = ""
        ElseIf xs = 54 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\54.jpg")
            Lblach.Visible = True
            Lblname.Text = "LENSON MORAS"
            Lblbat.Text = "LEFT HAND"
            Lblball.Text = ""
            LBLwick.Text = "YES"
            Lblach.Text = "SACRED HEART COLLEGE TEAM"
            Lbldept.Text = "2ND BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 61 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblach.Visible = True
            Lblname.Text = "Hemanth PV"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "RIGHT HAND"
            LBLwick.Text = ""
            Lblach.Text = "COORG PRIEMER LEGUE,SIX AND FIX COORG"
            Lbldept.Text = ""
            lblallrounder.Text = ""
        ElseIf xs = 56 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\56.jpg")
            Lblname.Text = "MOHAMMAD SALEEM"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1ST BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 53 Then

            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\57.jpeg")
            Lblname.Text = "Yusuf"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = ""
            lblallrounder.Text = ""
        ElseIf xs = 58 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblname.Text = ""
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = ""
            lblallrounder.Text = ""
        ElseIf xs = 63 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblname.Text = ""
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = ""
            lblallrounder.Text = ""
        ElseIf xs = 60 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\60.jpg")
            Lblname.Text = "ZAMEER RAZAK"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        ElseIf xs = 55 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\61.jpeg")
            Lblname.Text = "RANJITH"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "2ND BA"
            lblallrounder.Text = ""
        ElseIf xs = 62 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\test.png")
            Lblname.Text = "SATHYASWAROOP"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = "RIGHT ARM"
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "1SR BA"
            lblallrounder.Text = "YES"
        ElseIf xs = 59 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\63.jpeg")
            Lblname.Text = "NAVEEN"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BA"
            lblallrounder.Text = ""
        ElseIf xs = 64 Then
            PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\images\64.jpeg")
            Lblname.Text = "RAKSHITH SHETTY"
            Lblbat.Text = "RIGHT HAND"
            Lblball.Text = ""
            LBLwick.Text = ""
            Lblach1.Text = ""
            Lbldept.Text = "3RD BCOM"
            lblallrounder.Text = ""
        Else
            MsgBox("not in the list")


        End If
    End Sub

    Private Sub GunaButton1_Click(sender As Object, e As EventArgs) Handles GunaButton1.Click
        Lblname.Text = ""
        Lblbat.Text = ""
        Lblball.Text = ""
        LBLwick.Text = ""
        Lblach.Visible = False
        Lblach.Text = ""
        Lbldept.Text = ""
        lblallrounder.Text = ""
        Label2.Text = ""
        PictureBox3.Image = Image.FromFile("D:\vbnet\SHPL\resources\test.png")
        txtreg.Text = ""
        Bid.Text = ""
        BidTeam.Text = ""


    End Sub

    Private Sub Bid_Click(sender As Object, e As EventArgs) Handles Bid.Click

    End Sub

    Private Sub ListBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListBox1.SelectedIndexChanged

    End Sub

    Private Sub GunaShadowPanel2_Paint(sender As Object, e As PaintEventArgs) Handles GunaShadowPanel2.Paint

    End Sub
End Class
